apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  name: etcd-client
  namespace: openshift-etcd-operator
